apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: vote-deploy
  namespace: voting-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote

  template:
    metadata:
      labels:
        app: vote 
    spec:
      containers:
      - name: frontend-vote
        image: rohaanraj/votingapp_vote:v1
        ports:
        - containerPort: 80

