apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db-deploy
  namespace: voting-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres-db
        image:  postgres:15-alpine       
        ports:
          - containerPort: 5432

        volumeMounts:
          - name: database
            mountPath: /var/lib/postgresql/data

        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: POSTGRES_USER

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD

      volumes:
      - name: database
        emptyDir: {}







