apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: voting-app
spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: db
  ports:
    - name: "db-service"
      port: {{ .Values.db.containerPort }}
      targetPort: {{ .Values.db.service.targetPort }}


