apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-deploy
  namespace: voting-app

spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-db
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: {{ .Values.redis.containerPort }}

        volumeMounts:
          - name: redis
            mountPath: /data

      volumes:
        - name: redis
          emptyDir: {}



