apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-page-deployment
  labels:
    app: result-page-deploy
  namespace: voting-app

spec:
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      app: result

  template:
    metadata:
      labels:
        app: result 
    spec:
      containers:
      - name: frontend-result
        image: {{ .Values.result.image }}
        ports:
          - name: ui
            containerPort: {{ .Values.result.containerPort }}

