apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: voting-app
spec:
  type: {{ .Values.vote.service.type }}
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: {{ .Values.vote.service.port }}
      targetPort: {{ .Values.vote.service.targetPort }}
      nodePort: {{ .Values.vote.service.nodePort }}

