pipeline{
	agent any

	stages{
		stage('Verify WS'){
			steps{
				dir('voting-app'){
					sh 'pwd'
				}
			}
		}
		stage('Get commit SHA'){
			steps{
				script{
					env.COMMIT_SHA = env.GIT_COMMIT.take(7)
					echo "Commit SHA: ${env.COMMIT_SHA}"
				}
			}
		}
		stage('Build Images'){
			parallel{

				stage('Build Vote'){
					steps{
						dir('voting-app'){
							sh """
								docker build -t vote:${env.COMMIT_SHA} vote
							"""
						}
					}
				}
				stage('Build Result'){
					steps{
						dir('voting-app'){
							sh """
								docker build -t result:${env.COMMIT_SHA} result
							"""
						}
					}
				}
				stage('Build Worker'){
					steps{
						dir('voting-app'){
							sh """
								docker build -t worker:${env.COMMIT_SHA} worker
							"""
						}
					}
				}
			}
		}
		
		stage('Login to ECR'){
			steps{
				sh """
				aws ecr get-login-password --region us-east-1 \
        | docker login \
        --username AWS \
        --password-stdin 889738907995.dkr.ecr.us-east-1.amazonaws.com
				"""
			}
		}

		stage('Push images to ECR'){
			steps{
				script{
					def ECR="889738907995.dkr.ecr.us-east-1.amazonaws.com"

					sh """
					docker tag vote:${env.COMMIT_SHA} $ECR/vote:${env.COMMIT_SHA}
					docker tag result:${env.COMMIT_SHA} $ECR/result:${env.COMMIT_SHA}
					docker tag worker:${env.COMMIT_SHA} $ECR/worker:${env.COMMIT_SHA}

					docker push $ECR/vote:${env.COMMIT_SHA}
					docker push $ECR/result:${env.COMMIT_SHA}
					docker push $ECR/worker:${env.COMMIT_SHA}
					"""
				}
			}
		}

		stage('Update Helm charts'){
			steps{
				dir('voting-app/helm/voting-test'){
					withCredentials([string(credentialsId: "github-creds", variable: "GITHUB_CREDS")]){
						sh """
							git config user.email "rohanraj.madanu@gmail.com"
							git config user.name "rohanraj"

							sed -i "s|tag:.*|tag: ${env.COMMIT_SHA}|g" values.yaml
							git add values.yaml
							git commit -m "Updated image tag " || true

							git push https://${GITHUB_CREDS}@github.com/RohaanRaj/ci-cd-pipelines.git HEAD:master
						"""
					}
				}
			}
		}
	}
}
