vote:
  replicaCount: 2
  image:     
    repository: 889738907995.dkr.ecr.us-east-1.amazonaws.com/vote
    tag: 47d394b
  containerPort: 80
  service:
    type: NodePort
    port: 8080
    targetPort: 80
    nodePort: 30880


result:
  replicaCount: 2
  image: 
    repository: 889738907995.dkr.ecr.us-east-1.amazonaws.com/result
    tag: 47d394b
  containerPort: 80
  service:
    type: NodePort
    ui:
      port: 8081
      targetPort: 80
      nodePort: 30881
    debug:
      port: 9229
      targetPort: 9229


worker:
  replicaCount: 3
  image: 
    repository: 889738907995.dkr.ecr.us-east-1.amazonaws.com/worker
    tag: 47d394b
  containerPort: 80


redis:
  replicaCount: 1
  image: redis:alpine
  containerPort: 6379
  service:
    type: ClusterIP
    targetPort: 6379

postgres:
  user: postgres

db:
  replicaCount: 1
  image: postgres:15-alpine
  containerPort: 5432
  service:
    type: ClusterIP
    targetPort: 5432
